In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [5]:
df = pd.read_csv("../data/Cleaned_Dataset_IntermodalRail.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 257
Columns: 19

In [6]:
df.head()

,shipment_id,transport_mode,recorded_date,recorded_time,recorded_datetime,origin_location,destination_location,cargo_type,temperature_celsius,humidity_percentage,vibration_level,pressure_kpa,exposure_duration_hours,door_open_count,salinity_ppt,thermal_leakage_score,spoilage_risk_percent,remaining_shelf_life_days,spoilage_status
0,RAIL1001,Intermodal Rail,2025-07-18,10:00,2025-07-18 10:00:00,Mumbai,Kochi,Flowers,3.8,62.4,1.8,0.0,159.2,0,0.0,4.5,20.3,4.0,Fresh
1,RAIL0681,Intermodal Rail,2025-03-01,10:45,2025-03-01 10:45:00,Kolkata,Kochi,Flowers,4.5,47.4,4.3,0.0,143.1,0,0.0,4.3,13.5,4.7,Fresh
2,RAIL0086,Intermodal Rail,2024-11-09,01:05,2024-11-09 01:05:00,Kolkata,Bengaluru,Meat,3.1,35.8,0.4,0.0,141.9,0,0.0,3.2,18.7,5.2,Fresh
3,RAIL0432,Intermodal Rail,2024-11-30,04:35,2024-11-30 04:35:00,Kolkata,Jammu,Pharmaceuticals,7.2,50.7,2.6,0.0,153.1,0,0.0,1.4,8.3,28.2,Fresh
4,RAIL0624,Intermodal Rail,2025-06-25,08:15,2025-06-25 08:15:00,Mumbai,Nagpur,Fruits,11.5,34.1,3.0,0.0,140.2,0,0.0,3.4,8.8,11.0,Fresh

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   shipment_id                257 non-null    object
 1   transport_mode             257 non-null    object
 2   recorded_date              257 non-null    object
 3   recorded_time              257 non-null    object
 4   recorded_datetime          257 non-null    object
 5   origin_location            257 non-null    object
 6   destination_location       257 non-null    object
 7   cargo_type                 257 non-null    object
 8   temperature_celsius        257 non-null    float64
 9   humidity_percentage        257 non-null    float64
 10  vibration_level            257 non-null    float64
 11  pressure_kpa               257 non-null    float64
 12  exposure_duration_hours    257 non-null    float64
 13  door_open_count            257 non-null    int64
 14  salinity_ppt               257 non-null    float64
 15  thermal_leakage_score      257 non-null    float64
 16  spoilage_risk_percent      257 non-null    float64
 17  remaining_shelf_life_days  257 non-null    float64
 18  spoilage_status            257 non-null    object
dtypes: float64(9), int64(1), object(9)
memory usage: 38.3+ KB

In [8]:
df.describe(include="all")

,shipment_id,transport_mode,recorded_date,recorded_time,recorded_datetime,origin_location,destination_location,cargo_type,temperature_celsius,humidity_percentage,vibration_level,pressure_kpa,exposure_duration_hours,door_open_count,salinity_ppt,thermal_leakage_score,spoilage_risk_percent,remaining_shelf_life_days,spoilage_status
count,257,257,257,257,257,257,257,257,257.000000,257.000000,257.000000,257.0,257.000000,257.0,257.0,257.000000,257.000000,257.000000,257
unique,257,1,222,160,250,6,7,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
top,RAIL0057,Intermodal Rail,2026-08-02,20:35,2025-07-18 10:00:00,Kolkata,Jaipur,Flowers,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fresh
freq,1,257,3,4,2,48,46,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,238
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.904280,61.494163,2.534241,0.0,142.291051,0.0,0.0,4.431518,17.000389,8.997276,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.980021,15.146523,0.895864,0.0,13.410157,0.0,0.0,2.084012,11.421739,7.318205,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-5.000000,30.000000,0.400000,0.0,120.100000,0.0,0.0,0.200000,1.000000,1.500000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.300000,52.000000,1.900000,0.0,130.600000,0.0,0.0,3.000000,11.800000,4.700000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.900000,60.400000,2.500000,0.0,141.900000,0.0,0.0,4.600000,16.000000,6.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.500000,70.700000,3.100000,0.0,153.900000,0.0,0.0,5.800000,19.900000,10.200000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.000000,95.000000,4.900000,0.0,167.600000,0.0,0.0,9.500000,94.200000,29.100000,NaN