In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("data/cleaned/Cleaned_Dataset_AirFreight.csv")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

df.head()

Rows: 257
Columns: 19

,shipment_id,transport_mode,recorded_date,recorded_time,recorded_datetime,origin_location,destination_location,cargo_type,temperature_celsius,humidity_percentage,vibration_level,pressure_kpa,exposure_duration_hours,door_open_count,salinity_ppt,thermal_leakage_score,spoilage_risk_percent,remaining_shelf_life_days,spoilage_status
0,AIR1001,Air Freight,2026-06-25,05:40,2026-06-25 05:40:00,Kolkata Airport,Dubai Airport,Meat,1.1,34.2,2.5,91.1,42.6,0,0.0,0.0,27.3,5.0,At Risk
1,AIR0283,Air Freight,2026-06-23,11:10,2026-06-23 11:10:00,Bengaluru Airport,Doha Airport,Seafood,3.2,24.6,0.9,86.6,28.4,0,0.0,0.0,17.4,3.6,Fresh
2,AIR0237,Air Freight,2026-03-19,17:05,2026-03-19 17:05:00,Mumbai Airport,Frankfurt Airport,Meat,3.6,35.5,3.0,87.7,37.3,0,0.0,0.0,22.9,4.5,Fresh
3,AIR0829,Air Freight,2025-03-15,12:35,2025-03-15 12:35:00,Hyderabad Airport,Amsterdam Airport,Meat,1.6,39.4,0.7,84.4,29.1,0,0.0,0.0,13.9,5.2,Fresh
4,AIR0976,Air Freight,2026-01-20,03:15,2026-01-20 03:15:00,Chennai Airport,Dubai Airport,Fruits,4.1,35.7,5.6,77.3,35.0,0,0.0,0.0,16.2,10.9,Fresh

In [3]:
import os
print(os.getcwd())

C:\Users\sanni bhuwad\OneDrive\Documents\GitHub\Infotact-project\AtmoSync

In [4]:
import os

print(os.listdir(".."))

['.git', '.gitattributes', 'AtmoSync', 'README.md', 'sani', 'Sani.txt']

In [6]:
import os
print(os.getcwd())

C:\Users\sanni bhuwad\OneDrive\Documents\GitHub\Infotact-project\AtmoSync

In [8]:
import os

print("Current folder:")
print(os.getcwd())

print("\nFolders/files inside AtmoSync:")
for item in os.listdir("."):
    print(item)

Current folder:
C:\Users\sanni bhuwad\OneDrive\Documents\GitHub\Infotact-project\AtmoSync

Folders/files inside AtmoSync:
.gitignore
.ipynb_checkpoints
01_data_exploration.ipynb
anaconda_projects
dashboard
data
dbt
docs
kafka
notebooks
README.md
requirements.txt
sql

In [9]:
import os

for root, dirs, files in os.walk("."):
    for file in files:
        if file.lower().endswith(".csv"):
            print(os.path.join(root, file))

.\data\cleaned\Cleaned_Dataset_AirFreight.csv

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 257 entries, 0 to 256
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   shipment_id                257 non-null    str
 1   transport_mode             257 non-null    str
 2   recorded_date              257 non-null    str
 3   recorded_time              257 non-null    str
 4   recorded_datetime          257 non-null    str
 5   origin_location            257 non-null    str
 6   destination_location       257 non-null    str
 7   cargo_type                 257 non-null    str
 8   temperature_celsius        257 non-null    float64
 9   humidity_percentage        257 non-null    float64
 10  vibration_level            257 non-null    float64
 11  pressure_kpa               257 non-null    float64
 12  exposure_duration_hours    257 non-null    float64
 13  door_open_count            257 non-null    int64
 14  salinity_ppt               257 non-null    float64
 15  thermal_leakage_score      257 non-null    float64
 16  spoilage_risk_percent      257 non-null    float64
 17  remaining_shelf_life_days  257 non-null    float64
 18  spoilage_status            257 non-null    str
dtypes: float64(9), int64(1), str(9)
memory usage: 62.5 KB

In [12]:
df.describe(include="all")

,shipment_id,transport_mode,recorded_date,recorded_time,recorded_datetime,origin_location,destination_location,cargo_type,temperature_celsius,humidity_percentage,vibration_level,pressure_kpa,exposure_duration_hours,door_open_count,salinity_ppt,thermal_leakage_score,spoilage_risk_percent,remaining_shelf_life_days,spoilage_status
count,257,257,257,257,257,257,257,257,257.000000,257.000000,257.000000,257.000000,257.000000,257.0,257.0,257.0,257.000000,257.000000,257
unique,257,1,221,166,250,6,7,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
top,AIR1001,Air Freight,2025-01-02,07:40,2026-06-25 05:40:00,Hyderabad Airport,Doha Airport,Pharmaceuticals,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Fresh
freq,1,257,3,5,2,55,47,44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,222
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.264202,27.889105,1.260311,85.175875,36.368093,0.0,0.0,0.0,19.838911,10.135409,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.089285,9.525224,1.309334,6.981603,6.684397,0.0,0.0,0.0,13.978649,8.409469,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-11.900000,8.000000,0.100000,62.000000,24.100000,0.0,0.0,0.0,3.200000,2.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.200000,21.700000,0.600000,81.300000,30.600000,0.0,0.0,0.0,14.100000,4.700000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.200000,28.400000,0.900000,86.000000,36.200000,0.0,0.0,0.0,17.500000,6.300000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.800000,34.300000,1.200000,89.900000,42.100000,0.0,0.0,0.0,21.300000,10.400000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,37.900000,49.500000,6.100000,100.400000,47.900000,0.0,0.0,0.0,96.900000,29.700000,NaN

In [14]:
print("Missing values:")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Missing values:
shipment_id                  0
transport_mode               0
recorded_date                0
recorded_time                0
recorded_datetime            0
origin_location              0
destination_location         0
cargo_type                   0
temperature_celsius          0
humidity_percentage          0
vibration_level              0
pressure_kpa                 0
exposure_duration_hours      0
door_open_count              0
salinity_ppt                 0
thermal_leakage_score        0
spoilage_risk_percent        0
remaining_shelf_life_days    0
spoilage_status              0
dtype: int64

Duplicate rows: 0

In [15]:
"data/cleaned/Cleaned_Dataset_AirFreight.csv"

'data/cleaned/Cleaned_Dataset_AirFreight.csv'